version: '3.8'

services:
  face-recognition-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map port 5000 of the container to port 5000 on the host
    volumes:
      - ./app:/app  # Mount the local 'app' directory to '/app' in the container
    environment:
      INPUT_STREAM_URL: "${INPUT_STREAM_URL}"
      OUTPUT_HOST: "${OUTPUT_HOST}"
      OUTPUT_PORT: "${OUTPUT_PORT}"
      OUTPUT_PATH: "${OUTPUT_PATH}"
      IMAGE_DIRECTORY: "${IMAGE_DIRECTORY}"
      NOTIFICATION_SERVICE_URL: "${NOTIFICATION_SERVICE_URL}"
      OUTPUT_WIDTH: "${OUTPUT_WIDTH}"
      OUTPUT_HEIGHT: "${OUTPUT_HEIGHT}"
