version: '3.8'

services:
  videostream:
    build:
      context: ..
      dockerfile: dockerfile.videostream
    ports:
      - "8000:5000"  # Umgebungsvariable für den Host-Port
    volumes:
      - ./data:/data  # Mount the local 'data' directory to '/data' in the container
      - ./app:/app
    depends_on:
      - configserver

  configserver:
    build:
      context: ..
      dockerfile: dockerfile.configserver
    ports:
      - "8080:5000"  # Umgebungsvariable für den Host-Port
    volumes:
      - ./data:/data  # Mount the local 'data' directory to '/data' in the container
      - ./app:/app
