import os

# Konfiguration aus Umgebungsvariablen
INPUT_STREAM_URL = os.getenv('INPUT_STREAM_URL', '/dev/video0')
OUTPUT_HOST = os.getenv('OUTPUT_HOST', '0.0.0.0')
OUTPUT_PORT = int(os.getenv('OUTPUT_PORT', '5000'))
OUTPUT_PATH = os.getenv('OUTPUT_PATH', '/video')
IMAGE_DIRECTORY = os.getenv('IMAGE_DIRECTORY', '/default/path/if/not/set')
NOTIFICATION_SERVICE_URL = os.getenv('NOTIFICATION_SERVICE_URL')
OVERLAY_TRANSPARENCY = float(os.getenv('OVERLAY_TRANSPARENCY', 0.2))
OUTPUT_WIDTH = int(os.getenv('OUTPUT_WIDTH', 640))
OUTPUT_HEIGHT = int(os.getenv('OUTPUT_HEIGHT', 480))


print("Configuration:")
print(f"INPUT_STREAM_URL: {INPUT_STREAM_URL}")
print(f"OUTPUT_HOST: {OUTPUT_HOST}")
print(f"OUTPUT_PORT: {OUTPUT_PORT}")
print(f"OUTPUT_PATH: {OUTPUT_PATH}")
print(f"IMAGE_DIRECTORY: {IMAGE_DIRECTORY}")
print(f"NOTIFICATION_SERVICE_URL: {NOTIFICATION_SERVICE_URL}")
print(f"OVERLAY_TRANSPARENCY: {OVERLAY_TRANSPARENCY}")
print(f"OUTPUT_WIDTH: {OUTPUT_WIDTH}")
print(f"OUTPUT_HEIGHT: {OUTPUT_HEIGHT}")
